steps:
  - label: ':hammer: tox build, test, and release'
    if: build.branch == "master"
    id: toxic-docker-release
    command: "./.buildkite/release.sh"
    artifact_paths: 
      - ".tox/report/tmp/*"
      - ".tox/mypy/tmp/*"
      - ".tox/flake8/tmp/*"
      - ".tox/dist/*.zip"
      - ".tox/py*-test/tmp/xunit-result.xml"
      - ".tox/py*-test/log/*.log"
    plugins:
      - docker#v3.3.0:
          workdir: /repo
          image: "uavcan/toxic:py35-py38-sq"
          propagate-environment: true
          environment:
            - "SONARQUBE_TOKEN"
            - "PYPI_PASSWORD"
    agents:
      queue: 'default'
    timeout_in_minutes: 15

