#!/usr/bin/env python3
#
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# This software is distributed under the terms of the MIT License.
#
"""
The Nanaimo CLI.
"""

import sys
import argparse


def _make_parser() -> argparse.ArgumentParser:
    """
    Provided for documentation purposes only (sphinx-argparse). Do not use.
    """
    import nanaimo.cli
    return nanaimo.cli._make_parser()


if __name__ == "__main__":
    import nanaimo.cli
    sys.exit(nanaimo.cli.main())
