#!/usr/bin/env python3
#
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# This software is distributed under the terms of the MIT License.
#
"""
    Command-line script for uploading, monitoring, and reporting googletest
    binaries in parallel.
"""

import sys
import argparse


def _make_parser() -> argparse.ArgumentParser:
    """
    Provided for documentation purposes only (sphinx-argparse). Do not use.
    """
    import nanaimo
    return nanaimo._make_parser()


if __name__ == "__main__":
    import nanaimo
    sys.exit(nanaimo.main())
